### ISSUE TITLE
Support the built in Remote Explorer plugin

### ISSUE THREAD

**Issue by jacobrosenthal** [long-rock/blue-space#7]
Hi all!

We talked briefly last round, and a new round approaches! I would love for this to work out of the box with the current plugin shipped with the game even with a reduced feature/configuration set. That way people can try out your miner and presumably theyll eventualyl want to 'upgrade' to your plugin to get your better features.

What would it take to support the /mine endpoint and spec?

**Comment by fracek** [comment]
I started working on this, I just need to finish it up and it's ready to go.

**Comment by fracek** [comment]
I need to fix the build in #8 and the miner will be compatible with the default plugin.

**Comment by fracek** [comment]
Currently packaging is blocked by [this issue](https://gitlab.kitware.com/cmake/cmake/-/issues/21702). Tomorrow I'll look for a work around this.

**Comment by fracek** [comment]
I released a new version that  is compatible with the default plugin. https://github.com/long-rock/blue-space/releases/tag/v0.4.0-0
